import { describe, expect, it } from 'vitest'
import ts from 'typescript'

import {
  TYPEGEN_VERSION,
  emitTypesModule,
  modelIdsKey,
  moduleNames,
  typesEtag,
} from './typegen.ts'

/** Typecheck `source` as a standalone module with the real compiler. */
function diagnostics(
  source: string,
  overrides: Partial<ts.CompilerOptions> = {},
): Array<string> {
  const fileName = '/generated.ts'
  const options: ts.CompilerOptions = {
    strict: true,
    noEmit: true,
    skipLibCheck: true,
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    ...overrides,
  }
  const host = ts.createCompilerHost(options)
  const getSourceFile = host.getSourceFile.bind(host)
  host.getSourceFile = (name, languageVersion, ...rest) =>
    name === fileName
      ? ts.createSourceFile(fileName, source, ts.ScriptTarget.ES2022, true)
      : getSourceFile(name, languageVersion, ...rest)
  const fileExists = host.fileExists.bind(host)
  host.fileExists = (name) => name === fileName || fileExists(name)
  const program = ts.createProgram([fileName], options, host)
  return ts
    .getPreEmitDiagnostics(program)
    .map((d) => ts.flattenDiagnosticMessageText(d.messageText, '\n'))
}

/** Messages-shaped bundled schema exercising the emitter's full subset. */
const fixture = {
  type: 'object',
  description: 'Create a message.',
  required: ['model', 'messages', 'max_tokens'],
  properties: {
    model: { type: 'string', description: 'Model id, e.g. claude-sonnet-4-6.' },
    max_tokens: { type: 'integer' },
    temperature: { type: 'number', nullable: true },
    stream: { type: 'boolean', default: false },
    stop_sequences: { type: 'array', items: { type: 'string' } },
    messages: { type: 'array', items: { $ref: '#/$defs/Message' } },
    tool_choice: {
      oneOf: [
        { $ref: '#/$defs/ToolChoiceAuto' },
        { $ref: '#/$defs/ToolChoiceTool' },
      ],
    },
    metadata: {
      type: 'object',
      additionalProperties: { type: 'string' },
    },
    'odd-key': { const: 42 },
    coords: {
      type: 'array',
      prefixItems: [{ type: 'number' }, { type: 'number' }],
      items: false,
    },
    legacy: {
      deprecated: true,
      description: 'Ends with a tricky */ sequence.',
      type: ['string', 'null'],
    },
  },
  $defs: {
    Message: {
      type: 'object',
      required: ['role', 'content'],
      properties: {
        role: { enum: ['user', 'assistant'] },
        content: {
          anyOf: [
            { type: 'string' },
            { type: 'array', items: { $ref: '#/$defs/ContentBlock' } },
          ],
        },
        // Circular: a message can quote another message.
        quoted: { $ref: '#/$defs/Message' },
      },
    },
    ContentBlock: {
      allOf: [
        {
          type: 'object',
          required: ['type'],
          properties: { type: { type: 'string' } },
        },
        { type: 'object', properties: { text: { type: 'string' } } },
      ],
    },
    ToolChoiceAuto: {
      type: 'object',
      required: ['type'],
      properties: { type: { const: 'auto' } },
      additionalProperties: false,
    },
    ToolChoiceTool: {
      type: 'object',
      required: ['type', 'name'],
      properties: { type: { const: 'tool' }, name: { type: 'string' } },
    },
    // Collides with the reserved alias name.
    JsonSchema: { type: 'object', properties: { ok: { type: 'boolean' } } },
  },
} satisfies Record<string, unknown>

function emitFixture(optionalStyle?: 'exact' | 'undefined') {
  return emitTypesModule({
    provider: 'anthropic',
    endpointId: 'v1/messages',
    kind: 'input',
    contentHash: 'abc123def456',
    schema: fixture,
    optionalStyle,
    sourceUrl:
      'https://modelschemas.com/v1/schemas/anthropic/text/v1/messages?kind=input',
  })
}

describe('emitTypesModule', () => {
  it('compiles clean under strict, with and without exactOptionalPropertyTypes', () => {
    const source = emitFixture()
    expect(diagnostics(source)).toEqual([])
    expect(diagnostics(source, { exactOptionalPropertyTypes: true })).toEqual(
      [],
    )
    expect(
      diagnostics(emitFixture('undefined'), {
        exactOptionalPropertyTypes: true,
      }),
    ).toEqual([])
  })

  it('emits the documented module shape', () => {
    const source = emitFixture()
    expect(source).toContain(
      `@generated by modelschemas typegen v${TYPEGEN_VERSION}`,
    )
    expect(source).toContain('// schema version: abc123def456')
    expect(source).toContain(
      'export const anthropicV1MessagesRequestSchema: JsonSchema =',
    )
    expect(source).toContain('export interface AnthropicV1MessagesRequest {')
    // Required vs optional, with exact style by default.
    expect(source).toContain('model: string')
    expect(source).toContain('temperature?: number | null')
    // Enum union + const literal + quoted member names.
    expect(source).toContain('role: "user" | "assistant"')
    expect(source).toContain('"odd-key"?: 42')
    // Tuple, typed record, $defs as exported declarations.
    expect(source).toContain('coords?: [number, number]')
    expect(source).toContain('metadata?: Record<string, string>')
    expect(source).toContain('export interface Message {')
    expect(source).toContain('quoted?: Message')
    // allOf intersection, closed object.
    expect(source).toContain('export type ContentBlock =')
    expect(source).toContain('@deprecated')
    // Zero imports, zero `any`.
    expect(source).not.toMatch(/^import /m)
    expect(source).not.toMatch(/: any\b/)
  })

  it('renames $defs that collide with reserved names', () => {
    const source = emitFixture()
    expect(source).toContain('export interface JsonSchema2 {')
    expect(source).toContain('export type JsonSchema = ')
  })

  it('optionalStyle=undefined widens optional members', () => {
    const source = emitFixture('undefined')
    expect(source).toContain('stream?: boolean | undefined')
  })

  it('is deterministic', () => {
    expect(emitFixture()).toBe(emitFixture())
  })

  it('handles boolean and ref-rooted schemas', () => {
    const refRooted = emitTypesModule({
      provider: 'openai',
      endpointId: 'chat/completions',
      kind: 'output',
      contentHash: 'deadbeef',
      schema: {
        $ref: '#/$defs/Completion',
        $defs: {
          Completion: {
            type: 'object',
            required: ['id'],
            properties: { id: { type: 'string' } },
          },
        },
      },
    })
    expect(refRooted).toContain(
      'export type OpenaiChatCompletionsResponse = Completion',
    )
    expect(diagnostics(refRooted)).toEqual([])
  })

  it('overlays model as Known | ListedModelId when modelIds are passed', () => {
    const source = emitFixture()
    expect(source).toContain('model: string')
    expect(source).not.toContain('ListedModelId')

    const overlaid = emitTypesModule({
      provider: 'anthropic',
      endpointId: 'v1/messages',
      kind: 'input',
      contentHash: 'abc123def456',
      schema: fixture,
      modelIds: ['claude-sonnet-4-5', 'claude-opus-4-1'],
    })
    expect(overlaid).toContain('export type ListedModelId')
    expect(overlaid).toContain(
      'model: "claude-opus-4-1" | "claude-sonnet-4-5" | ListedModelId<"anthropic">',
    )
    expect(overlaid).not.toMatch(/^import /m)
    expect(diagnostics(overlaid)).toEqual([])
  })

  it('does not overlay output schemas or schemas without a model field', () => {
    const output = emitTypesModule({
      provider: 'anthropic',
      endpointId: 'v1/messages',
      kind: 'output',
      contentHash: 'abc',
      schema: fixture,
      modelIds: ['claude-sonnet-4-5'],
    })
    expect(output).not.toContain('ListedModelId')

    const noModel = emitTypesModule({
      provider: 'fal',
      endpointId: 'fal-ai/flux/dev',
      kind: 'input',
      contentHash: 'abc',
      schema: {
        type: 'object',
        properties: { prompt: { type: 'string' } },
      },
      modelIds: ['fal-ai/flux/dev'],
    })
    expect(noModel).not.toContain('ListedModelId')
  })

  it('keys the types ETag by the live model list, not the schema hash', () => {
    const hash = 'f'.repeat(64)
    expect(typesEtag(hash, 'exact', modelIdsKey(['b', 'a']))).toBe(
      typesEtag(hash, 'exact', modelIdsKey(['a', 'b'])),
    )
    expect(typesEtag(hash, 'exact', modelIdsKey(['a']))).not.toBe(
      typesEtag(hash, 'exact', modelIdsKey(['a', 'c'])),
    )
    expect(typesEtag(hash, 'exact')).not.toContain('-m')
  })

  it('accepts a structural ListedModelId from the client on an overlaid request', () => {
    const module = emitTypesModule({
      provider: 'anthropic',
      endpointId: 'v1/messages',
      kind: 'input',
      contentHash: 'abc123def456',
      schema: fixture,
      modelIds: ['claude-sonnet-4-5'],
    })
    const listed = `
type ClientListed<TProvider extends string = string> = string & {
  readonly __modelschemasListed: TProvider
}
declare function asListed<TProvider extends string>(
  provider: TProvider,
  rawId: string,
): ClientListed<TProvider>
const body: AnthropicV1MessagesRequest = {
  model: asListed("anthropic", "brand-new"),
  max_tokens: 1,
  messages: [{ role: "user", content: "hi" }],
}
`
    expect(diagnostics(module + listed)).toEqual([])
    expect(
      diagnostics(
        module +
          `
const bad: AnthropicV1MessagesRequest = {
  model: "totally-new",
  max_tokens: 1,
  messages: [{ role: "user", content: "hi" }],
}
`,
      ),
    ).not.toEqual([])
  })

  it('derives stable export names', () => {
    expect(moduleNames('anthropic', 'v1/messages', 'input')).toEqual({
      rootType: 'AnthropicV1MessagesRequest',
      schemaConst: 'anthropicV1MessagesRequestSchema',
    })
    expect(
      moduleNames('elevenlabs', 'v1/text-to-speech/{voice_id}', 'output')
        .rootType,
    ).toBe('ElevenlabsV1TextToSpeechVoiceIdResponse')
  })
})

/**
 * `model` accepts a snapshot literal *or* a value that came from
 * `listModels` (a branded string). An arbitrary string — literal or
 * variable — is not assignable. TypeScript cannot see the live catalog
 * members; the brand only records provenance.
 */
describe('listed-model brand (Known | ListedModelId)', () => {
  const prelude = `
type ListedModelId<TProvider extends string = string> = string & {
  readonly __modelschemasListed: TProvider
}
type KnownModel = "claude-sonnet-4-5" | "claude-opus-4-1"
type Model = KnownModel | ListedModelId<"anthropic">
interface ChatRequest {
  model: Model
  max_tokens: number
}
declare function send(req: ChatRequest): void
declare function listModels(): Array<ListedModelId<"anthropic">>
`

  function check(statement: string): Array<string> {
    return diagnostics(`${prelude}\n${statement}`)
  }

  it('accepts a model that was in the build-time snapshot', () => {
    expect(
      check('send({ model: "claude-sonnet-4-5", max_tokens: 1024 })'),
    ).toEqual([])
  })

  it('accepts a model id returned by listModels, even if it is not in the snapshot', () => {
    expect(check('send({ model: listModels()[0], max_tokens: 1024 })')).toEqual(
      [],
    )
  })

  it('rejects a string literal that is not in the snapshot', () => {
    expect(check('send({ model: "totally-new", max_tokens: 1024 })')).toEqual([
      `Type '"totally-new"' is not assignable to type 'Model'.`,
    ])
  })

  it('rejects an arbitrary string variable', () => {
    expect(
      check(
        'const id: string = "claude-sonnet-4-5"; send({ model: id, max_tokens: 1024 })',
      ),
    ).toEqual([`Type 'string' is not assignable to type 'Model'.`])
  })

  it('still rejects a wrong max_tokens when the model came from listModels', () => {
    expect(
      check('send({ model: listModels()[0], max_tokens: "nope" })'),
    ).toEqual(["Type 'string' is not assignable to type 'number'."])
  })
})
