/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a0213396e0a91911fd44cb0818970c29)
interface __BaseEnv_Env {
	SCHEMA_CACHE: KVNamespace;
	DB: D1Database;
	EMAIL: SendEmail;
	ADMIN_KEY: string;
	ANTHROPIC_API_KEY: string;
	ARK_API_KEY: string;
	ASSEMBLYAI_API_KEY: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	BFL_API_KEY: string;
	CARTESIA_API_KEY: string;
	CEREBRAS_API_KEY: string;
	COHERE_API_KEY: string;
	DASHSCOPE_API_KEY: string;
	DEEPGRAM_API_KEY: string;
	DEEPSEEK_API_KEY: string;
	ELEVENLABS_API_KEY: string;
	FAL_KEY: string;
	FIREWORKS_API_KEY: string;
	GEMINI_API_KEY: string;
	GROQ_API_KEY: string;
	HYPERBOLIC_API_KEY: string;
	JINA_API_KEY: string;
	KLING_API_KEY: string;
	MISTRAL_API_KEY: string;
	MOONSHOT_API_KEY: string;
	NOVITA_API_KEY: string;
	OPENAI_API_KEY: string;
	PERPLEXITY_API_KEY: string;
	REPLICATE_API_TOKEN: string;
	RUNWAY_API_KEY: string;
	SAMBANOVA_API_KEY: string;
	SEED_SPEECH_API_KEY: string;
	STABILITY_API_KEY: string;
	TOGETHER_API_KEY: string;
	VOYAGE_API_KEY: string;
	XAI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_KEY" | "ANTHROPIC_API_KEY" | "ARK_API_KEY" | "ASSEMBLYAI_API_KEY" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "BFL_API_KEY" | "CARTESIA_API_KEY" | "CEREBRAS_API_KEY" | "COHERE_API_KEY" | "DASHSCOPE_API_KEY" | "DEEPGRAM_API_KEY" | "DEEPSEEK_API_KEY" | "ELEVENLABS_API_KEY" | "FAL_KEY" | "FIREWORKS_API_KEY" | "GEMINI_API_KEY" | "GROQ_API_KEY" | "HYPERBOLIC_API_KEY" | "JINA_API_KEY" | "KLING_API_KEY" | "MISTRAL_API_KEY" | "MOONSHOT_API_KEY" | "NOVITA_API_KEY" | "OPENAI_API_KEY" | "PERPLEXITY_API_KEY" | "REPLICATE_API_TOKEN" | "RUNWAY_API_KEY" | "SAMBANOVA_API_KEY" | "SEED_SPEECH_API_KEY" | "STABILITY_API_KEY" | "TOGETHER_API_KEY" | "VOYAGE_API_KEY" | "XAI_API_KEY">> {}
}
