/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8bfd7da3a1c8694b96a946343b684bc0)
interface __BaseEnv_Env {
	SCHEMA_CACHE: KVNamespace;
	DB: D1Database;
	DATABASE_URL: string;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	ANTHROPIC_API_KEY: string;
	ADMIN_KEY: string;
	PROD_ADMIN_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "ANTHROPIC_API_KEY" | "ADMIN_KEY" | "PROD_ADMIN_KEY">> {}
}
