/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8f3c3ee9bbca43f360b132e4b1307b65)
interface __BaseEnv_Env {
	SCHEMA_CACHE: KVNamespace;
	DB: D1Database;
	EMAIL: SendEmail;
	ANTHROPIC_API_KEY: string;
	DOPPLER_CONFIG: string;
	DOPPLER_ENVIRONMENT: string;
	DOPPLER_PROJECT: string;
	ELEVENLABS_API_KEY: string;
	FAL_KEY: string;
	GEMINI_API_KEY: string;
	OPENAI_API_KEY: string;
	XAI_API_KEY: string;
	ADMIN_KEY: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	ARK_API_KEY: string;
	SEED_SPEECH_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ANTHROPIC_API_KEY" | "DOPPLER_CONFIG" | "DOPPLER_ENVIRONMENT" | "DOPPLER_PROJECT" | "ELEVENLABS_API_KEY" | "FAL_KEY" | "GEMINI_API_KEY" | "OPENAI_API_KEY" | "XAI_API_KEY" | "ADMIN_KEY" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "ARK_API_KEY" | "SEED_SPEECH_API_KEY">> {}
}
