// @generated by modelschemas — do not edit; refresh with `modelschemas update`.
// provider: openrouter · endpoint: videos/google/veo-3.1 · kind: input
// source: https://modelschemas.com/v1/schemas/openrouter/video/videos/google/veo-3.1?kind=input
// schema version: 3e1af1a152264809e9ccbee3b01ee69d6b3d46997f8e279fd5a5194335b88226

export type JsonSchema = { readonly [key: string]: unknown }

export const openrouterVideosGoogleVeo31RequestSchema: JsonSchema = {
  $defs: {
    ContentPartAudio: {
      example: {
        audio_url: {
          url: 'https://example.com/audio.mp3',
        },
        type: 'audio_url',
      },
      properties: {
        audio_url: {
          properties: {
            url: {
              type: 'string',
            },
          },
          required: ['url'],
          type: 'object',
        },
        type: {
          enum: ['audio_url'],
          type: 'string',
        },
      },
      required: ['type', 'audio_url'],
      type: 'object',
    },
    ContentPartImage: {
      example: {
        image_url: {
          url: 'https://example.com/image.png',
        },
        type: 'image_url',
      },
      properties: {
        image_url: {
          properties: {
            url: {
              type: 'string',
            },
          },
          required: ['url'],
          type: 'object',
        },
        type: {
          enum: ['image_url'],
          type: 'string',
        },
      },
      required: ['type', 'image_url'],
      type: 'object',
    },
    ContentPartVideo: {
      example: {
        type: 'video_url',
        video_url: {
          url: 'https://example.com/clip.mp4',
        },
      },
      properties: {
        type: {
          enum: ['video_url'],
          type: 'string',
        },
        video_url: {
          properties: {
            url: {
              type: 'string',
            },
          },
          required: ['url'],
          type: 'object',
        },
      },
      required: ['type', 'video_url'],
      type: 'object',
    },
    FrameImage: {
      allOf: [
        {
          $ref: '#/$defs/ContentPartImage',
        },
        {
          properties: {
            frame_type: {
              description:
                'Whether this image represents the first or last frame of the video',
              enum: ['first_frame', 'last_frame'],
              example: 'first_frame',
              type: 'string',
              'x-speakeasy-unknown-values': 'allow',
            },
          },
          required: ['frame_type'],
          type: 'object',
        },
      ],
      example: {
        image_url: {
          url: 'https://example.com/image.png',
        },
        type: 'image_url',
      },
    },
    InputReference: {
      description:
        'A reference asset used to guide video generation. Image references are supported by all providers; audio and video references are only honored by providers that support them (currently BytePlus Seedance 2.0).',
      discriminator: {
        mapping: {
          audio_url: '#/components/schemas/ContentPartAudio',
          image_url: '#/components/schemas/ContentPartImage',
          video_url: '#/components/schemas/ContentPartVideo',
        },
        propertyName: 'type',
      },
      example: {
        image_url: {
          url: 'https://example.com/image.png',
        },
        type: 'image_url',
      },
      oneOf: [
        {
          $ref: '#/$defs/ContentPartImage',
        },
        {
          $ref: '#/$defs/ContentPartAudio',
        },
        {
          $ref: '#/$defs/ContentPartVideo',
        },
      ],
    },
    ProviderOptions: {
      description:
        'Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.',
      example: {
        openai: {
          max_tokens: 1000,
        },
      },
      properties: {
        '01ai': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        ai21: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'aion-labs': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        akashml: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        alibaba: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'amazon-bedrock': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'amazon-nova': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        ambient: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        anthropic: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        anyscale: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'arcee-ai': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'atlas-cloud': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        atoma: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        avian: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        azure: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        baidu: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        baseten: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'black-forest-labs': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        byteplus: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        centml: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        cerebras: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        chutes: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        cirrascale: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        clarifai: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        cloudflare: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        cohere: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        crofai: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        crucible: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        crusoe: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        darkbloom: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        decart: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        deepinfra: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        deepseek: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        dekallm: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        digitalocean: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        enfer: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'fake-provider': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        featherless: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        fireworks: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        friendli: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        gmicloud: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'google-ai-studio': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'google-vertex': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        gopomelo: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        groq: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        huggingface: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        hyperbolic: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'hyperbolic-quantized': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        inception: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        inceptron: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'inference-net': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        infermatic: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        inflection: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        inocloud: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'io-net': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        ionstream: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        klusterai: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        lambda: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        lepton: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        liquid: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        lynn: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'lynn-private': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        mancer: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'mancer-old': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        mara: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        meta: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        minimax: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        mistral: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        modal: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        modelrun: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        modular: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        moonshotai: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        morph: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        ncompass: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        nebius: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'nex-agi': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        nextbit: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        nineteen: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        novita: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        nvidia: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        octoai: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'open-inference': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        openai: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        parasail: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        perceptron: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        perplexity: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        phala: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        poolside: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        recraft: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        recursal: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        reflection: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        reka: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        relace: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        replicate: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        sambanova: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'sambanova-cloaked': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        seed: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'sf-compute': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        siliconflow: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        sourceful: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        stealth: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        stepfun: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        streamlake: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        switchpoint: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        targon: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        together: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'together-lite': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        ubicloud: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        upstage: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        venice: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        wafer: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        wandb: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        xai: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        xiaomi: {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
        'z-ai': {
          additionalProperties: {
            nullable: true,
          },
          type: 'object',
        },
      },
      type: 'object',
    },
  },
  description:
    "Google: Veo 3.1 (google/veo-3.1) — model-constrained video generation request. Google's state-of-the-art video generation model, built for maximum visual fidelity in final production cuts. Veo 3.1 generates high-quality 1080p video from text or image prompts with native synchronized audio —...",
  example: {
    aspect_ratio: '16:9',
    duration: 8,
    model: 'google/veo-3.1',
    prompt: 'A serene mountain landscape at sunset',
    resolution: '720p',
  },
  properties: {
    aspect_ratio: {
      description: 'Aspect ratio of the generated video',
      enum: ['16:9', '9:16'],
      example: '16:9',
      type: 'string',
      'x-speakeasy-unknown-values': 'allow',
    },
    callback_url: {
      description:
        'URL to receive a webhook notification when the video generation job completes. Overrides the workspace-level default callback URL if set. Must be HTTPS.',
      example: 'https://example.com/webhook',
      format: 'uri',
      type: 'string',
    },
    duration: {
      description: 'Duration of the generated video in seconds',
      enum: [4, 6, 8],
      example: 8,
      minimum: 1,
      type: 'integer',
    },
    frame_images: {
      description:
        'Images to use as the first and/or last frame of the generated video. Each image must specify a frame_type of first_frame or last_frame. Frame types supported by this model: first_frame, last_frame.',
      items: {
        $ref: '#/$defs/FrameImage',
      },
      type: 'array',
    },
    generate_audio: {
      description:
        "Whether to generate audio alongside the video. Defaults to the endpoint's generate_audio capability flag, false if not set.",
      example: true,
      type: 'boolean',
    },
    input_references: {
      description:
        'Reference assets to guide video generation. Accepts image, audio, and video references. Audio and video references are only honored by providers that support them (currently BytePlus Seedance 2.0); other providers use image references and ignore the rest.',
      items: {
        $ref: '#/$defs/InputReference',
      },
      type: 'array',
    },
    model: {
      description: 'Model id (fixed for this model-constrained schema)',
      enum: ['google/veo-3.1'],
      type: 'string',
    },
    prompt: {
      type: 'string',
    },
    provider: {
      description:
        'Provider-specific passthrough configuration Passthrough parameters allowed for this model: personGeneration, aspectRatio, negativePrompt, conditioningScale, enhancePrompt.',
      properties: {
        options: {
          allOf: [
            {
              $ref: '#/$defs/ProviderOptions',
            },
            {
              example: {
                'google-vertex': {
                  output_config: {
                    effort: 'low',
                  },
                },
              },
            },
          ],
        },
      },
      type: 'object',
    },
    resolution: {
      description: 'Resolution of the generated video',
      enum: ['720p', '1080p', '4K'],
      example: '720p',
      type: 'string',
      'x-speakeasy-unknown-values': 'allow',
    },
    seed: {
      description:
        'If specified, the generation will sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism is not guaranteed for all providers.',
      type: 'integer',
    },
    size: {
      description:
        'Exact pixel dimensions of the generated video in "WIDTHxHEIGHT" format (e.g. "1280x720"). Interchangeable with resolution + aspect_ratio.',
      enum: [
        '1280x720',
        '1080x1920',
        '1920x1080',
        '720x1280',
        '3840x2160',
        '2160x3840',
      ],
      example: '1280x720',
      type: 'string',
    },
  },
  required: ['prompt', 'model'],
  type: 'object',
}
