import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { ResolvedConfig } from 'vite'

import { modelschemas } from './index.ts'
import type { ModelschemasOptions } from './index.ts'

const HASH_A = 'a'.repeat(64)
const HASH_B = 'b'.repeat(64)

const TYPES_BODY = [
  '// @generated by modelschemas typegen v1',
  'export type JsonSchema = { readonly [key: string]: unknown }',
  'export const anthropicV1MessagesRequestSchema: JsonSchema = {}',
  'export interface AnthropicV1MessagesRequest { model: string }',
  '',
].join('\n')

/** Minimal fake of the live service for one input-only chat endpoint. */
function fakeService() {
  let requests = 0
  const fetchImpl: typeof fetch = (input, init) => {
    requests++
    const { pathname, searchParams } = new URL(String(input))
    const headers = new Headers(init?.headers)
    if (pathname === '/v1/schemas/anthropic') {
      return Promise.resolve(
        Response.json({
          provider: 'anthropic',
          activities: { chat: ['v1/messages'] },
        }),
      )
    }
    if (pathname === '/v1/schemas/anthropic/chat/v1/messages') {
      if (searchParams.get('kind') === 'output') {
        return Promise.resolve(
          Response.json(
            { error: { code: 'unknown_schema', message: 'no output' } },
            { status: 404 },
          ),
        )
      }
      const etag = `"${HASH_A}-types-v1-exact"`
      if (headers.get('if-none-match') === etag) {
        return Promise.resolve(new Response(null, { status: 304 }))
      }
      return Promise.resolve(new Response(TYPES_BODY, { headers: { etag } }))
    }
    if (pathname === '/v1/changes') {
      return Promise.resolve(
        Response.json({
          changes: [
            {
              type: 'schema.updated',
              subjectId: 'anthropic/v1/messages',
              summary: 'Updated input schema for /v1/messages',
              payload: { kind: 'input', contentHash: HASH_B },
            },
          ],
          nextCursor: null,
        }),
      )
    }
    return Promise.resolve(
      Response.json(
        { error: { code: 'not_found', message: pathname } },
        { status: 404 },
      ),
    )
  }
  return { fetchImpl, requestCount: () => requests }
}

let outDir: string

beforeEach(async () => {
  outDir = await mkdtemp(join(tmpdir(), 'modelschemas-vite-'))
})

afterEach(async () => {
  await rm(outDir, { recursive: true, force: true })
})

interface FakeLogger {
  info: ReturnType<typeof vi.fn>
  warn: ReturnType<typeof vi.fn>
}

function drive(pluginOptions: ModelschemasOptions, command: 'serve' | 'build') {
  const plugin = modelschemas(pluginOptions)
  const logger: FakeLogger = { info: vi.fn(), warn: vi.fn() }
  const config = { command, root: '/tmp', logger } as unknown as ResolvedConfig
  const configResolved = plugin.configResolved as (c: ResolvedConfig) => void
  configResolved(config)
  const buildStart = plugin.buildStart as () => Promise<void>
  return { run: buildStart, logger }
}

function options(
  fetchImpl: typeof fetch,
  overrides: Partial<ModelschemasOptions> = {},
): ModelschemasOptions {
  return {
    baseUrl: 'https://svc.test',
    outDir, // absolute — root is ignored
    selections: ['anthropic'],
    fetchImpl,
    ...overrides,
  }
}

describe('serve mode', () => {
  it('pulls missing modules, then reports (not applies) upstream updates', async () => {
    const { fetchImpl } = fakeService()
    const { run, logger } = drive(options(fetchImpl), 'serve')
    await run()

    const file = await readFile(
      join(outDir, 'anthropic', 'v1-messages.request.ts'),
      'utf8',
    )
    expect(file).toContain('AnthropicV1MessagesRequest')

    // The fake changes feed reports HASH_B upstream vs HASH_A pulled —
    // surfaced as a log, file untouched.
    const messages = logger.info.mock.calls.map((c) => String(c[0]))
    expect(messages.some((m) => m.includes('update(s) available'))).toBe(true)
    expect(file).not.toContain(HASH_B)
  })

  it('generated modules are import-clean: no imports, no side effects, no barrel', async () => {
    const { fetchImpl } = fakeService()
    const { run } = drive(options(fetchImpl), 'serve')
    await run()

    const file = await readFile(
      join(outDir, 'anthropic', 'v1-messages.request.ts'),
      'utf8',
    )
    // No top-level statement other than pure exports (tree-shakeable, no
    // side effects) — declaration keywords at column 0 must be export-led.
    expect(file).not.toMatch(
      /^(import|const|let|var|function|class|console|if|for|while)\b/m,
    )
    expect(file).toMatch(/^export (type|const|interface) /m)
    // And no barrel: nothing re-exported from elsewhere.
    expect(file).not.toMatch(/export \* from|export \{[^}]*\} from/)
  })
})

describe('build mode', () => {
  it('fails with remediation when nothing was pulled, without touching the network', async () => {
    const { fetchImpl, requestCount } = fakeService()
    const { run } = drive(options(fetchImpl), 'build')
    await expect(run()).rejects.toThrow(/modelschemas pull/)
    expect(requestCount()).toBe(0)
  })

  it('passes offline once the committed files match the manifest', async () => {
    const { fetchImpl } = fakeService()
    const serve = drive(options(fetchImpl), 'serve')
    await serve.run()

    const offline = fakeService()
    const build = drive(options(offline.fetchImpl), 'build')
    await expect(build.run()).resolves.toBeUndefined()
    expect(offline.requestCount()).toBe(0)
  })
})
