import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { readManifest } from './manifest.ts'
import { checkUpdates, pull, verify } from './pull.ts'
import type { PullConfig } from './pull.ts'

const HASH_A = 'a'.repeat(64)
const HASH_B = 'b'.repeat(64)

const TYPES_BODY = [
  '// @generated by modelschemas typegen v1',
  'export type JsonSchema = { readonly [key: string]: unknown }',
  'export const anthropicV1MessagesRequestSchema: JsonSchema = {}',
  'export interface AnthropicV1MessagesRequest { model: string }',
  '',
].join('\n')

interface Call {
  url: string
  ifNoneMatch: string | null
  authorization: string | null
}

/** Fake service: provider index + one chat endpoint with input-only schema. */
function fakeService(options: { hash?: string } = {}) {
  const hash = options.hash ?? HASH_A
  const calls: Array<Call> = []
  const fetchImpl: typeof fetch = (input, init) => {
    const url = String(input)
    const headers = new Headers(init?.headers)
    calls.push({
      url,
      ifNoneMatch: headers.get('if-none-match'),
      authorization: headers.get('authorization'),
    })
    const { pathname, searchParams } = new URL(url)

    if (pathname === '/v1/schemas/anthropic') {
      return Promise.resolve(
        Response.json({
          provider: 'anthropic',
          activities: { chat: ['v1/messages'] },
        }),
      )
    }
    if (pathname === '/v1/schemas/anthropic/chat/v1/messages') {
      // No output schema for this endpoint.
      if (searchParams.get('kind') === 'output') {
        return Promise.resolve(
          Response.json(
            { error: { code: 'unknown_schema', message: 'no output' } },
            { status: 404 },
          ),
        )
      }
      const etag =
        searchParams.get('format') === 'types'
          ? `"${hash}-types-v1-${searchParams.get('optional') ?? 'exact'}"`
          : `"${hash}"`
      if (headers.get('if-none-match') === etag) {
        return Promise.resolve(new Response(null, { status: 304 }))
      }
      if (searchParams.get('format') === 'types') {
        return Promise.resolve(
          new Response(TYPES_BODY, {
            headers: {
              etag,
              'content-type': 'text/typescript; charset=utf-8',
            },
          }),
        )
      }
      return Promise.resolve(
        Response.json(
          { contentHash: hash, schema: { type: 'object' } },
          { headers: { etag } },
        ),
      )
    }
    if (pathname === '/v1/changes') {
      return Promise.resolve(
        Response.json({
          changes: [
            {
              type: 'schema.updated',
              subjectId: 'anthropic/v1/messages',
              summary: 'Updated input schema for /v1/messages',
              payload: { kind: 'input', contentHash: HASH_B },
            },
          ],
          nextCursor: null,
        }),
      )
    }
    return Promise.resolve(
      Response.json(
        { error: { code: 'not_found', message: pathname } },
        { status: 404 },
      ),
    )
  }
  return { fetchImpl, calls }
}

let outDir: string

beforeEach(async () => {
  outDir = await mkdtemp(join(tmpdir(), 'modelschemas-codegen-'))
})

afterEach(async () => {
  await rm(outDir, { recursive: true, force: true })
})

function config(overrides: Partial<PullConfig> = {}): PullConfig {
  return {
    baseUrl: 'https://svc.test',
    outDir,
    selections: ['anthropic'],
    ...overrides,
  }
}

describe('pull', () => {
  it('writes generated modules + manifest; implicit missing kinds are skipped', async () => {
    const { fetchImpl } = fakeService()
    const summary = await pull(config({ fetchImpl }), { now: () => 1000 })

    expect(summary.written).toEqual(['anthropic/chat/v1/messages#request'])
    expect(summary.skipped).toEqual(['anthropic/chat/v1/messages#response'])
    expect(summary.failed).toEqual([])

    const file = await readFile(
      join(outDir, 'anthropic', 'v1-messages.request.ts'),
      'utf8',
    )
    expect(file).toContain('AnthropicV1MessagesRequest')

    const manifest = await readManifest(outDir)
    expect(manifest?.fetchedAt).toBe(1000)
    expect(manifest?.entries['anthropic/chat/v1/messages#request']).toEqual({
      path: join('anthropic', 'v1-messages.request.ts'),
      contentHash: HASH_A,
      etag: `"${HASH_A}-types-v1-exact"`,
    })
  })

  it('an explicit kind with no schema is a failure, not a skip', async () => {
    const { fetchImpl } = fakeService()
    const summary = await pull(
      config({ fetchImpl, selections: ['anthropic/v1/messages#response'] }),
    )
    expect(summary.failed).toEqual([
      expect.objectContaining({ key: 'anthropic/chat/v1/messages#response' }),
    ])
  })

  it('replays ETags: second pull sends If-None-Match and short-circuits on 304', async () => {
    const { fetchImpl, calls } = fakeService()
    await pull(config({ fetchImpl }), { now: () => 1000 })
    const again = await pull(config({ fetchImpl }), { now: () => 2000 })

    expect(again.written).toEqual([])
    expect(again.unchanged).toEqual(['anthropic/chat/v1/messages#request'])
    const conditional = calls.filter((c) => c.ifNoneMatch !== null)
    expect(conditional).toHaveLength(1)
    // fetchedAt is only bumped when something changed.
    expect((await readManifest(outDir))?.fetchedAt).toBe(1000)
  })

  it('missingOnly trusts existing files without any schema request', async () => {
    const { fetchImpl } = fakeService()
    await pull(config({ fetchImpl }))
    const { fetchImpl: second, calls } = fakeService()
    const summary = await pull(config({ fetchImpl: second }), {
      missingOnly: true,
    })
    expect(summary.unchanged).toEqual(['anthropic/chat/v1/messages#request'])
    // Only the catalog index (+ the still-missing response side) is fetched.
    expect(calls.map((c) => new URL(c.url).searchParams.get('kind'))).toEqual([
      null,
      'output',
    ])
  })

  it('types:false wraps the JSON schema in a const-only module locally', async () => {
    const { fetchImpl } = fakeService()
    await pull(config({ fetchImpl, types: false }))
    const file = await readFile(
      join(outDir, 'anthropic', 'v1-messages.request.ts'),
      'utf8',
    )
    expect(file).toContain('anthropicV1MessagesRequestSchema')
    // The user's own prettier may reformat (here: the repo config) — assert
    // content, not formatting.
    expect(file).toMatch(/["']?type["']?:\s*["']object["']/)
    expect(file).not.toContain('interface')
  })

  it('sends the api key as a bearer header', async () => {
    const { fetchImpl, calls } = fakeService()
    await pull(config({ fetchImpl, apiKey: 'msk_test' }))
    expect(calls.every((c) => c.authorization === 'Bearer msk_test')).toBe(true)
  })
})

describe('verify', () => {
  it('fails without a manifest, with remediation', async () => {
    const result = await verify(config())
    expect(result.ok).toBe(false)
    expect(result.problems[0]).toContain('modelschemas pull')
  })

  it('passes after a pull; fails when a file vanishes or selections grow', async () => {
    const { fetchImpl } = fakeService()
    await pull(config({ fetchImpl }))
    expect((await verify(config())).ok).toBe(true)

    expect(
      (await verify(config({ selections: ['anthropic', 'openai'] }))).problems,
    ).toEqual([expect.stringContaining("Selection 'openai'")])

    await rm(join(outDir, 'anthropic', 'v1-messages.request.ts'))
    const result = await verify(config())
    expect(result.ok).toBe(false)
    expect(result.problems[0]).toContain('v1-messages.request.ts')
  })
})

describe('checkUpdates', () => {
  it('reports entries whose upstream hash moved, and nothing otherwise', async () => {
    const { fetchImpl } = fakeService()
    await pull(config({ fetchImpl }))

    const updates = await checkUpdates(config({ fetchImpl }))
    expect(updates).toEqual([
      {
        key: 'anthropic/chat/v1/messages#request',
        contentHash: HASH_B,
        summary: 'Updated input schema for /v1/messages',
      },
    ])

    // Manifest already at HASH_B → silence.
    const manifest = await readManifest(outDir)
    if (manifest === null) throw new Error('manifest missing')
    const entry = manifest.entries['anthropic/chat/v1/messages#request']
    if (entry === undefined) throw new Error('entry missing')
    entry.contentHash = HASH_B
    await writeFile(
      join(outDir, '.manifest.json'),
      JSON.stringify(manifest, null, 2),
    )
    expect(await checkUpdates(config({ fetchImpl }))).toEqual([])
  })

  it('returns [] with no manifest', async () => {
    const { fetchImpl } = fakeService()
    expect(await checkUpdates(config({ fetchImpl }))).toEqual([])
  })
})
