/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillRouteImport } from './routes/skill'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as AuthDotmdRouteImport } from './routes/auth[.]md'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1IndexRouteImport } from './routes/v1/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as V1ValidateRouteImport } from './routes/v1/validate'
import { Route as V1StatusRouteImport } from './routes/v1/status'
import { Route as V1ChangesRouteImport } from './routes/v1/changes'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known/api-catalog'
import { Route as DotwellKnownAgentConfigurationRouteImport } from './routes/[.]well-known/agent-configuration'
import { Route as V1SubscriptionsIndexRouteImport } from './routes/v1/subscriptions/index'
import { Route as V1ProvidersIndexRouteImport } from './routes/v1/providers/index'
import { Route as V1ModelsIndexRouteImport } from './routes/v1/models/index'
import { Route as V1SubscriptionsIdRouteImport } from './routes/v1/subscriptions/$id'
import { Route as V1AgentsRegisterKeyRouteImport } from './routes/v1/agents/register-key'
import { Route as V1AgentsMeRouteImport } from './routes/v1/agents/me'
import { Route as ModelsProviderModelIdRouteImport } from './routes/models/$provider.$modelId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known/mcp/server-card[.]json'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known/agent-skills/index[.]json'
import { Route as V1SchemasProviderIndexRouteImport } from './routes/v1/schemas/$provider/index'
import { Route as V1ProvidersProviderModelsRouteImport } from './routes/v1/providers/$provider.models'
import { Route as V1ModelsProviderModelIdRouteImport } from './routes/v1/models/$provider.$modelId'
import { Route as V1AdminSyncProviderRouteImport } from './routes/v1/admin/sync.$provider'
import { Route as SchemasProviderActivitySplatRouteImport } from './routes/schemas/$provider.$activity.$'
import { Route as V1SchemasProviderActivityIndexRouteImport } from './routes/v1/schemas/$provider/$activity/index'
import { Route as V1SchemasProviderActivitySplatRouteImport } from './routes/v1/schemas/$provider/$activity/$'

const SkillRoute = SkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDotmdRoute = AuthDotmdRouteImport.update({
  id: '/auth.md',
  path: '/auth.md',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1IndexRoute = V1IndexRouteImport.update({
  id: '/v1/',
  path: '/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ValidateRoute = V1ValidateRouteImport.update({
  id: '/v1/validate',
  path: '/v1/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StatusRoute = V1StatusRouteImport.update({
  id: '/v1/status',
  path: '/v1/status',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ChangesRoute = V1ChangesRouteImport.update({
  id: '/v1/changes',
  path: '/v1/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentConfigurationRoute =
  DotwellKnownAgentConfigurationRouteImport.update({
    id: '/.well-known/agent-configuration',
    path: '/.well-known/agent-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SubscriptionsIndexRoute = V1SubscriptionsIndexRouteImport.update({
  id: '/v1/subscriptions/',
  path: '/v1/subscriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ProvidersIndexRoute = V1ProvidersIndexRouteImport.update({
  id: '/v1/providers/',
  path: '/v1/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ModelsIndexRoute = V1ModelsIndexRouteImport.update({
  id: '/v1/models/',
  path: '/v1/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SubscriptionsIdRoute = V1SubscriptionsIdRouteImport.update({
  id: '/v1/subscriptions/$id',
  path: '/v1/subscriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AgentsRegisterKeyRoute = V1AgentsRegisterKeyRouteImport.update({
  id: '/v1/agents/register-key',
  path: '/v1/agents/register-key',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AgentsMeRoute = V1AgentsMeRouteImport.update({
  id: '/v1/agents/me',
  path: '/v1/agents/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsProviderModelIdRoute = ModelsProviderModelIdRouteImport.update({
  id: '/models/$provider/$modelId',
  path: '/models/$provider/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SchemasProviderIndexRoute = V1SchemasProviderIndexRouteImport.update({
  id: '/v1/schemas/$provider/',
  path: '/v1/schemas/$provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ProvidersProviderModelsRoute =
  V1ProvidersProviderModelsRouteImport.update({
    id: '/v1/providers/$provider/models',
    path: '/v1/providers/$provider/models',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1ModelsProviderModelIdRoute = V1ModelsProviderModelIdRouteImport.update({
  id: '/v1/models/$provider/$modelId',
  path: '/v1/models/$provider/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminSyncProviderRoute = V1AdminSyncProviderRouteImport.update({
  id: '/v1/admin/sync/$provider',
  path: '/v1/admin/sync/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasProviderActivitySplatRoute =
  SchemasProviderActivitySplatRouteImport.update({
    id: '/schemas/$provider/$activity/$',
    path: '/schemas/$provider/$activity/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SchemasProviderActivityIndexRoute =
  V1SchemasProviderActivityIndexRouteImport.update({
    id: '/v1/schemas/$provider/$activity/',
    path: '/v1/schemas/$provider/$activity/',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SchemasProviderActivitySplatRoute =
  V1SchemasProviderActivitySplatRouteImport.update({
    id: '/v1/schemas/$provider/$activity/$',
    path: '/v1/schemas/$provider/$activity/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth.md': typeof AuthDotmdRoute
  '/changes': typeof ChangesRoute
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill': typeof SkillRoute
  '/.well-known/agent-configuration': typeof DotwellKnownAgentConfigurationRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/v1/changes': typeof V1ChangesRoute
  '/v1/status': typeof V1StatusRoute
  '/v1/validate': typeof V1ValidateRoute
  '/models/': typeof ModelsIndexRoute
  '/v1/': typeof V1IndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/models/$provider/$modelId': typeof ModelsProviderModelIdRoute
  '/v1/agents/me': typeof V1AgentsMeRoute
  '/v1/agents/register-key': typeof V1AgentsRegisterKeyRoute
  '/v1/subscriptions/$id': typeof V1SubscriptionsIdRoute
  '/v1/models/': typeof V1ModelsIndexRoute
  '/v1/providers/': typeof V1ProvidersIndexRoute
  '/v1/subscriptions/': typeof V1SubscriptionsIndexRoute
  '/schemas/$provider/$activity/$': typeof SchemasProviderActivitySplatRoute
  '/v1/admin/sync/$provider': typeof V1AdminSyncProviderRoute
  '/v1/models/$provider/$modelId': typeof V1ModelsProviderModelIdRoute
  '/v1/providers/$provider/models': typeof V1ProvidersProviderModelsRoute
  '/v1/schemas/$provider/': typeof V1SchemasProviderIndexRoute
  '/v1/schemas/$provider/$activity/$': typeof V1SchemasProviderActivitySplatRoute
  '/v1/schemas/$provider/$activity/': typeof V1SchemasProviderActivityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth.md': typeof AuthDotmdRoute
  '/changes': typeof ChangesRoute
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill': typeof SkillRoute
  '/.well-known/agent-configuration': typeof DotwellKnownAgentConfigurationRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/v1/changes': typeof V1ChangesRoute
  '/v1/status': typeof V1StatusRoute
  '/v1/validate': typeof V1ValidateRoute
  '/models': typeof ModelsIndexRoute
  '/v1': typeof V1IndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/models/$provider/$modelId': typeof ModelsProviderModelIdRoute
  '/v1/agents/me': typeof V1AgentsMeRoute
  '/v1/agents/register-key': typeof V1AgentsRegisterKeyRoute
  '/v1/subscriptions/$id': typeof V1SubscriptionsIdRoute
  '/v1/models': typeof V1ModelsIndexRoute
  '/v1/providers': typeof V1ProvidersIndexRoute
  '/v1/subscriptions': typeof V1SubscriptionsIndexRoute
  '/schemas/$provider/$activity/$': typeof SchemasProviderActivitySplatRoute
  '/v1/admin/sync/$provider': typeof V1AdminSyncProviderRoute
  '/v1/models/$provider/$modelId': typeof V1ModelsProviderModelIdRoute
  '/v1/providers/$provider/models': typeof V1ProvidersProviderModelsRoute
  '/v1/schemas/$provider': typeof V1SchemasProviderIndexRoute
  '/v1/schemas/$provider/$activity/$': typeof V1SchemasProviderActivitySplatRoute
  '/v1/schemas/$provider/$activity': typeof V1SchemasProviderActivityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth.md': typeof AuthDotmdRoute
  '/changes': typeof ChangesRoute
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill': typeof SkillRoute
  '/.well-known/agent-configuration': typeof DotwellKnownAgentConfigurationRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/v1/changes': typeof V1ChangesRoute
  '/v1/status': typeof V1StatusRoute
  '/v1/validate': typeof V1ValidateRoute
  '/models/': typeof ModelsIndexRoute
  '/v1/': typeof V1IndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/models/$provider/$modelId': typeof ModelsProviderModelIdRoute
  '/v1/agents/me': typeof V1AgentsMeRoute
  '/v1/agents/register-key': typeof V1AgentsRegisterKeyRoute
  '/v1/subscriptions/$id': typeof V1SubscriptionsIdRoute
  '/v1/models/': typeof V1ModelsIndexRoute
  '/v1/providers/': typeof V1ProvidersIndexRoute
  '/v1/subscriptions/': typeof V1SubscriptionsIndexRoute
  '/schemas/$provider/$activity/$': typeof SchemasProviderActivitySplatRoute
  '/v1/admin/sync/$provider': typeof V1AdminSyncProviderRoute
  '/v1/models/$provider/$modelId': typeof V1ModelsProviderModelIdRoute
  '/v1/providers/$provider/models': typeof V1ProvidersProviderModelsRoute
  '/v1/schemas/$provider/': typeof V1SchemasProviderIndexRoute
  '/v1/schemas/$provider/$activity/$': typeof V1SchemasProviderActivitySplatRoute
  '/v1/schemas/$provider/$activity/': typeof V1SchemasProviderActivityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth.md'
    | '/changes'
    | '/docs'
    | '/examples'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/openapi.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skill'
    | '/.well-known/agent-configuration'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/v1/changes'
    | '/v1/status'
    | '/v1/validate'
    | '/models/'
    | '/v1/'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/auth/$'
    | '/models/$provider/$modelId'
    | '/v1/agents/me'
    | '/v1/agents/register-key'
    | '/v1/subscriptions/$id'
    | '/v1/models/'
    | '/v1/providers/'
    | '/v1/subscriptions/'
    | '/schemas/$provider/$activity/$'
    | '/v1/admin/sync/$provider'
    | '/v1/models/$provider/$modelId'
    | '/v1/providers/$provider/models'
    | '/v1/schemas/$provider/'
    | '/v1/schemas/$provider/$activity/$'
    | '/v1/schemas/$provider/$activity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth.md'
    | '/changes'
    | '/docs'
    | '/examples'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/openapi.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skill'
    | '/.well-known/agent-configuration'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/v1/changes'
    | '/v1/status'
    | '/v1/validate'
    | '/models'
    | '/v1'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/auth/$'
    | '/models/$provider/$modelId'
    | '/v1/agents/me'
    | '/v1/agents/register-key'
    | '/v1/subscriptions/$id'
    | '/v1/models'
    | '/v1/providers'
    | '/v1/subscriptions'
    | '/schemas/$provider/$activity/$'
    | '/v1/admin/sync/$provider'
    | '/v1/models/$provider/$modelId'
    | '/v1/providers/$provider/models'
    | '/v1/schemas/$provider'
    | '/v1/schemas/$provider/$activity/$'
    | '/v1/schemas/$provider/$activity'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth.md'
    | '/changes'
    | '/docs'
    | '/examples'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/openapi.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skill'
    | '/.well-known/agent-configuration'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/v1/changes'
    | '/v1/status'
    | '/v1/validate'
    | '/models/'
    | '/v1/'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/auth/$'
    | '/models/$provider/$modelId'
    | '/v1/agents/me'
    | '/v1/agents/register-key'
    | '/v1/subscriptions/$id'
    | '/v1/models/'
    | '/v1/providers/'
    | '/v1/subscriptions/'
    | '/schemas/$provider/$activity/$'
    | '/v1/admin/sync/$provider'
    | '/v1/models/$provider/$modelId'
    | '/v1/providers/$provider/models'
    | '/v1/schemas/$provider/'
    | '/v1/schemas/$provider/$activity/$'
    | '/v1/schemas/$provider/$activity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthDotmdRoute: typeof AuthDotmdRoute
  ChangesRoute: typeof ChangesRoute
  DocsRoute: typeof DocsRoute
  ExamplesRoute: typeof ExamplesRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillRoute: typeof SkillRoute
  DotwellKnownAgentConfigurationRoute: typeof DotwellKnownAgentConfigurationRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  V1ChangesRoute: typeof V1ChangesRoute
  V1StatusRoute: typeof V1StatusRoute
  V1ValidateRoute: typeof V1ValidateRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  V1IndexRoute: typeof V1IndexRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ModelsProviderModelIdRoute: typeof ModelsProviderModelIdRoute
  V1AgentsMeRoute: typeof V1AgentsMeRoute
  V1AgentsRegisterKeyRoute: typeof V1AgentsRegisterKeyRoute
  V1SubscriptionsIdRoute: typeof V1SubscriptionsIdRoute
  V1ModelsIndexRoute: typeof V1ModelsIndexRoute
  V1ProvidersIndexRoute: typeof V1ProvidersIndexRoute
  V1SubscriptionsIndexRoute: typeof V1SubscriptionsIndexRoute
  SchemasProviderActivitySplatRoute: typeof SchemasProviderActivitySplatRoute
  V1AdminSyncProviderRoute: typeof V1AdminSyncProviderRoute
  V1ModelsProviderModelIdRoute: typeof V1ModelsProviderModelIdRoute
  V1ProvidersProviderModelsRoute: typeof V1ProvidersProviderModelsRoute
  V1SchemasProviderIndexRoute: typeof V1SchemasProviderIndexRoute
  V1SchemasProviderActivitySplatRoute: typeof V1SchemasProviderActivitySplatRoute
  V1SchemasProviderActivityIndexRoute: typeof V1SchemasProviderActivityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skill': {
      id: '/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof SkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth.md': {
      id: '/auth.md'
      path: '/auth.md'
      fullPath: '/auth.md'
      preLoaderRoute: typeof AuthDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/': {
      id: '/v1/'
      path: '/v1'
      fullPath: '/v1/'
      preLoaderRoute: typeof V1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/validate': {
      id: '/v1/validate'
      path: '/v1/validate'
      fullPath: '/v1/validate'
      preLoaderRoute: typeof V1ValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/status': {
      id: '/v1/status'
      path: '/v1/status'
      fullPath: '/v1/status'
      preLoaderRoute: typeof V1StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/changes': {
      id: '/v1/changes'
      path: '/v1/changes'
      fullPath: '/v1/changes'
      preLoaderRoute: typeof V1ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-configuration': {
      id: '/.well-known/agent-configuration'
      path: '/.well-known/agent-configuration'
      fullPath: '/.well-known/agent-configuration'
      preLoaderRoute: typeof DotwellKnownAgentConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/subscriptions/': {
      id: '/v1/subscriptions/'
      path: '/v1/subscriptions'
      fullPath: '/v1/subscriptions/'
      preLoaderRoute: typeof V1SubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/providers/': {
      id: '/v1/providers/'
      path: '/v1/providers'
      fullPath: '/v1/providers/'
      preLoaderRoute: typeof V1ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/models/': {
      id: '/v1/models/'
      path: '/v1/models'
      fullPath: '/v1/models/'
      preLoaderRoute: typeof V1ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/subscriptions/$id': {
      id: '/v1/subscriptions/$id'
      path: '/v1/subscriptions/$id'
      fullPath: '/v1/subscriptions/$id'
      preLoaderRoute: typeof V1SubscriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/agents/register-key': {
      id: '/v1/agents/register-key'
      path: '/v1/agents/register-key'
      fullPath: '/v1/agents/register-key'
      preLoaderRoute: typeof V1AgentsRegisterKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/agents/me': {
      id: '/v1/agents/me'
      path: '/v1/agents/me'
      fullPath: '/v1/agents/me'
      preLoaderRoute: typeof V1AgentsMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$provider/$modelId': {
      id: '/models/$provider/$modelId'
      path: '/models/$provider/$modelId'
      fullPath: '/models/$provider/$modelId'
      preLoaderRoute: typeof ModelsProviderModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/schemas/$provider/': {
      id: '/v1/schemas/$provider/'
      path: '/v1/schemas/$provider'
      fullPath: '/v1/schemas/$provider/'
      preLoaderRoute: typeof V1SchemasProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/providers/$provider/models': {
      id: '/v1/providers/$provider/models'
      path: '/v1/providers/$provider/models'
      fullPath: '/v1/providers/$provider/models'
      preLoaderRoute: typeof V1ProvidersProviderModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/models/$provider/$modelId': {
      id: '/v1/models/$provider/$modelId'
      path: '/v1/models/$provider/$modelId'
      fullPath: '/v1/models/$provider/$modelId'
      preLoaderRoute: typeof V1ModelsProviderModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/sync/$provider': {
      id: '/v1/admin/sync/$provider'
      path: '/v1/admin/sync/$provider'
      fullPath: '/v1/admin/sync/$provider'
      preLoaderRoute: typeof V1AdminSyncProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/$provider/$activity/$': {
      id: '/schemas/$provider/$activity/$'
      path: '/schemas/$provider/$activity/$'
      fullPath: '/schemas/$provider/$activity/$'
      preLoaderRoute: typeof SchemasProviderActivitySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/schemas/$provider/$activity/': {
      id: '/v1/schemas/$provider/$activity/'
      path: '/v1/schemas/$provider/$activity'
      fullPath: '/v1/schemas/$provider/$activity/'
      preLoaderRoute: typeof V1SchemasProviderActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/schemas/$provider/$activity/$': {
      id: '/v1/schemas/$provider/$activity/$'
      path: '/v1/schemas/$provider/$activity/$'
      fullPath: '/v1/schemas/$provider/$activity/$'
      preLoaderRoute: typeof V1SchemasProviderActivitySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthDotmdRoute: AuthDotmdRoute,
  ChangesRoute: ChangesRoute,
  DocsRoute: DocsRoute,
  ExamplesRoute: ExamplesRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillRoute: SkillRoute,
  DotwellKnownAgentConfigurationRoute: DotwellKnownAgentConfigurationRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  V1ChangesRoute: V1ChangesRoute,
  V1StatusRoute: V1StatusRoute,
  V1ValidateRoute: V1ValidateRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  V1IndexRoute: V1IndexRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ModelsProviderModelIdRoute: ModelsProviderModelIdRoute,
  V1AgentsMeRoute: V1AgentsMeRoute,
  V1AgentsRegisterKeyRoute: V1AgentsRegisterKeyRoute,
  V1SubscriptionsIdRoute: V1SubscriptionsIdRoute,
  V1ModelsIndexRoute: V1ModelsIndexRoute,
  V1ProvidersIndexRoute: V1ProvidersIndexRoute,
  V1SubscriptionsIndexRoute: V1SubscriptionsIndexRoute,
  SchemasProviderActivitySplatRoute: SchemasProviderActivitySplatRoute,
  V1AdminSyncProviderRoute: V1AdminSyncProviderRoute,
  V1ModelsProviderModelIdRoute: V1ModelsProviderModelIdRoute,
  V1ProvidersProviderModelsRoute: V1ProvidersProviderModelsRoute,
  V1SchemasProviderIndexRoute: V1SchemasProviderIndexRoute,
  V1SchemasProviderActivitySplatRoute: V1SchemasProviderActivitySplatRoute,
  V1SchemasProviderActivityIndexRoute: V1SchemasProviderActivityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
